DROP TABLE SHARE;
CREATE TABLE SHARE(
DATE DATE UNIQUE,
OPEN DOUBLE PRECISION NOT NULL,
HIGH DOUBLE PRECISION NOT NULL,
LOW DOUBLE PRECISION NOT NULL,
CLOSE DOUBLE PRECISION NOT NULL,
VOLUME INT NOT NULL,
TOTALVALUE DOUBLE PRECISION   NULL
);

INSERT INTO SHARE VALUES('2011-11-11','2.88','2.99','2.77','2.89','198787','343432.4');